# 20210821 ItoMaru - Numpy

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(5,5)

array([[0.55533737, 0.24225445, 0.47403656, 0.7880594 , 0.43591765],
       [0.77920902, 0.74929838, 0.97991081, 0.53895309, 0.84678367],
       [0.54783983, 0.84340473, 0.64891114, 0.16342217, 0.96062823],
       [0.70579752, 0.14743395, 0.02830166, 0.97315319, 0.0057488 ],
       [0.62463233, 0.75305281, 0.07030471, 0.81329315, 0.10398999]])

In [27]:
np.random.randint(1,100,10)

array([52, 72, 73, 27, 46, 59, 37, 12, 53,  9])

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
randarr = np.random.randint(0,50,10)
randarr

array([ 1, 44, 12,  6, 39, 48, 15, 19, 30,  7])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
randarr

array([ 1, 44, 12,  6, 39, 48, 15, 19, 30,  7])

In [36]:
randarr.max()

48

In [37]:
randarr.min()

1

In [38]:
randarr

array([ 1, 44, 12,  6, 39, 48, 15, 19, 30,  7])

In [39]:
randarr.argmax()

5

In [40]:
randarr.argmin()

0

In [43]:
arr = arr.reshape(5,5)

In [44]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
arr.shape

(5, 5)

In [46]:
arr.dtype

dtype('int32')

In [49]:
from numpy.random import randint

In [53]:
randint(2,10)

9