In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

data = pd.read_csv("student-mat.csv")
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [3]:
data = data[["G1", "G2", "G3","studytime","failures","absences"]]
predict = "G3"
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

C:\Users\itomaru\Anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until


In [4]:
linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)
accuracy = linear_regression.score(xtest,ytest)
print(accuracy)

0.8566538514184097


In [5]:
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[11.84183188  3.60047109 10.70116692  7.08657517  3.60047109]
 [11.84183188 11.84183188 10.70116692  7.08657517 15.2458606 ]
 [11.53458517 -0.90657407 10.70116692  7.15686855 11.94647782]
 ...
 [11.94647782 -0.90657407 17.03709326  7.15686855  7.15686855]
 [12.7255332   5.8860754  17.03709326  7.08657517  7.08657517]
 [-0.90657407  5.47548559 17.03709326  7.08657517 11.84183188]] [[[15 12  2  1  0]
  [ 7  5  3  1  0]
  [11 11  1  0  0]
  [ 8  8  3  0  2]
  [ 7  5  3  1  0]]

 [[15 12  2  1  0]
  [15 12  2  1  0]
  [11 11  1  0  0]
  [ 8  8  3  0  2]
  [16 15  2  0  0]]

 [[10  9  2  0 75]
  [ 7  0  1  1  0]
  [11 11  1  0  0]
  [ 5  9  2  2  6]
  [13 12  3  0  6]]

 ...

 [[13 12  3  0  6]
  [ 7  0  1  1  0]
  [17 17  4  0  0]
  [ 5  9  2  2  6]
  [ 5  9  2  2  6]]

 [[12 13  2  0  2]
  [ 7  7  4  0  4]
  [17 17  4  0  0]
  [ 8  8  3  0  2]
  [ 8  8  3  0  2]]

 [[ 7  0  1  1  0]
  [ 8  7  2  3  8]
  [17 17  4  0  0]
  [ 8  8  3  0  2]
  [15 12  2  1  0]]] [array([[12,  0, 10, 10,  0]

[[11.84183188  3.60047109 10.70116692  7.08657517  3.60047109]
 [11.84183188 11.84183188 10.70116692  7.08657517 15.2458606 ]
 [11.53458517 -0.90657407 10.70116692  7.15686855 11.94647782]
 ...
 [11.94647782 -0.90657407 17.03709326  7.15686855  7.15686855]
 [12.7255332   5.8860754  17.03709326  7.08657517  7.08657517]
 [-0.90657407  5.47548559 17.03709326  7.08657517 11.84183188]] [[[15 12  2  1  0]
  [ 7  5  3  1  0]
  [11 11  1  0  0]
  [ 8  8  3  0  2]
  [ 7  5  3  1  0]]

 [[15 12  2  1  0]
  [15 12  2  1  0]
  [11 11  1  0  0]
  [ 8  8  3  0  2]
  [16 15  2  0  0]]

 [[10  9  2  0 75]
  [ 7  0  1  1  0]
  [11 11  1  0  0]
  [ 5  9  2  2  6]
  [13 12  3  0  6]]

 ...

 [[13 12  3  0  6]
  [ 7  0  1  1  0]
  [17 17  4  0  0]
  [ 5  9  2  2  6]
  [ 5  9  2  2  6]]

 [[12 13  2  0  2]
  [ 7  7  4  0  4]
  [17 17  4  0  0]
  [ 8  8  3  0  2]
  [ 8  8  3  0  2]]

 [[ 7  0  1  1  0]
  [ 8  7  2  3  8]
  [17 17  4  0  0]
  [ 8  8  3  0  2]
  [15 12  2  1  0]]] [array([[12,  0, 10, 10,  0]