In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

data = pd.read_csv("student-mat.csv")
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [2]:
data = data[["G1", "G2", "G3", "studytime", "failures","absences"]]
predict = "G3"
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x, y, test_size=0.2)

C:\Users\itomaru\Anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until


In [3]:
linear_regression = LinearRegression()
linear_regression.fit(xtrain,ytrain)
accuracy = linear_regression.score(xtest,ytest)
print(accuracy)

0.8728853293636437


In [4]:
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[18.20151293 13.12868558  9.42980322  7.35868029 13.12868558]
 [18.20151293 18.20151293  9.42980322  7.35868029 14.43735153]
 [ 9.50736053 10.62370386  9.42980322 11.01736279 11.01959616]
 ...
 [11.01959616 10.62370386 11.9431518  11.01736279 11.01736279]
 [ 8.24036934 14.24921234 11.9431518   7.35868029  7.35868029]
 [10.62370386 14.5676376  11.9431518   7.35868029 18.20151293]] [[[16 18  2  0  0]
  [14 13  2  0  4]
  [10 10  4  0  6]
  [ 5  9  2  2  6]
  [14 13  2  0  4]]

 [[16 18  2  0  0]
  [16 18  2  0  0]
  [10 10  4  0  6]
  [ 5  9  2  2  6]
  [15 14  2  1 20]]

 [[ 8 10  1  0  4]
  [10 11  2  0  4]
  [10 10  4  0  6]
  [13 11  3  0  8]
  [13 11  2  0  4]]

 ...

 [[13 11  2  0  4]
  [10 11  2  0  4]
  [12 12  2  0  6]
  [13 11  3  0  8]
  [13 11  3  0  8]]

 [[10  9  4  0  0]
  [15 14  2  0  4]
  [12 12  2  0  6]
  [ 5  9  2  2  6]
  [ 5  9  2  2  6]]

 [[10 11  2  0  4]
  [13 15  4  0  0]
  [12 12  2  0  6]
  [ 5  9  2  2  6]
  [16 18  2  0  0]]] [array([[19, 13, 11,  7, 13]